// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Name      string
	Cpf       string
	Secret    string
	Balance   int32
	CreatedAt pgtype.Timestamptz
	UpdateAt  pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Transfer struct {
	ID                   int64
	AccountOriginID      int64
	AccountDestinationID int64
	Amount               int32
	CreatedAt            pgtype.Timestamptz
	UpdateAt             pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}
